[".config/nvim"]
type = "git-repo"
url = "https://github.com/arrekyrt/config.nvim"
refreshPeriod = "48h"

[".config/gdb/gdb-dashboard"]
type = "git-repo"
url = "https://github.com/cyrus-and/gdb-dashboard"
refreshPeriod = "48h"

[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "48h"
