setopt extendedglob

if  [[ ! "$-" =~ "^i" ]]; then
	set +u
fi
# xdg fallback
if [[ -z "$XDG_CONFIG_HOME" ]]; then
	export XDG_CONFIG_HOME="$HOME/.config"
	export XDG_CACHE_HOME="$HOME/.cache"
	export XDG_DATA_HOME="$HOME/.local/share"
	export XDG_STATE_HOME="$HOME/.local/state"
	export XDG_RUNTIME_DIR="/run/user/$UID"
fi

# path
if (( ! ${path[(I)$HOME/.local/bin]} )); then
	path=($HOME/.local/bin $HOME/go/bin $HOME/.cargo/bin $HOME/.cabal/bin $path)
fi
# use ccache installed
if (( ${+commands[ccache]} )) && (( ! ${path[(I)/usr/lib/ccache/bin]} )) && [[ -d /usr/lib/ccache/bin ]]; then
	path=(/usr/lib/ccache/bin $path)
fi
export PATH

# environment.d
if ((ENVIRONMENTD_LOADED != 1)); then
	if [[ -d "$XDG_CONFIG_HOME/environment.d/" ]]; then
		while read envar; do
			[[ -n "$envar" ]] && eval "export $envar"
		done < $XDG_CONFIG_HOME/environment.d/^10-path.conf
	fi
fi

export ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"
export HISTFILE="$XDG_DATA_HOME/zsh/history"

# set COLORTERM in tmux
if [[ -n "$TMUX" ]]; then
	export COLORTERM=truecolor
fi
# Editor
export EDITOR='nvim'
# set custom folder
export REPO=~/src/repo
export LAB=~/src/lab
export PRO=~/src/projects
export TEMPLATES=~/src/templates
# tab size
export LESS="-x4"
# disable telemetry from the evil company
export DOTNET_CLI_TELEMETRY_OPTOUT=true
